 SELECT CURRENT_DATE FROM emp

SELECT CURRENT_TIMESTAMP FROM emp	

select sysdate from emp

SELECT
EXTRACT( YEAR FROM TO_DATE( '29-Apr-2020 05:30:20 ',  'DD-Mon-YYYY HH24:MI:SS' ) ) YEAR
FROM
emp
 
 SELECT
TO_DATE( '20 APR 2020', 'DD MON YYYY' )CONVERTED_DATE
FROM emp;
